### ISSUE TITLE
Strip compile results

### ISSUE THREAD

**Issue by rflaperuta** [paixaop/node-sodium#111]
After installing and compiling the lib, how can we make the size of the folder smaller?

Which folders inside node_modules/sodium can be deleted safely?

I hitting a size restriction when deploying to AWS lambda and I need to strip everything I can from the node_modules folder.

Thanks in advance.

**Comment by paixaop** [comment]
you should be able to remove every dependency listed in the devDependencies of package.json

"devDependencies": {
    "mdextract": "^1.0.0",
    "istanbul": ">=0.4.3",
    "mocha": ">=2.4.5",
    "mocha-istanbul": ">=0.2.0",
    "node-gyp": ">=3.3.1"
  }

in the production machine

**Comment by AgentME** [comment]
If node-sodium is installed as a dependency of a project, then the devDependencies won't be installed with it.

**Comment by rflaperuta** [comment]
It is installed as @AgentME mentioned.

My point is, during install it compiles the native parts, but leaves behind objects and extra folders, which arent needed for runtime (i guess).

Which folders inside sodium module can be delete without compromissing its function?

**Comment by nealgriffin** [comment]
I know this is an old-ish issue - but I'll contribute the process that I used to get this to work with Lambda. I built the node-sodium on an EC2 Instance configure with Amazon's Linux AMI. This is pretty straightforward - create the EC2 instance, ssh in and basically get node installed - I used nvm, but I really shouldn't have - I was just trying to make it work.

Once nvm was installed, I installed node v6.10.~ - v6.10 is currently what AWS Lambda is run on. I had to update NPM to the latest version as well because it was only at 3.x.

From there, I npm installed sodium and all was good. This created a file in ../build/Release/sodium.node. Dropping back to my local machine which is running OS X, I scp'd that file down. I then replaced the sodium.node in my local installation of sodium, rezipped my lambda and re-uploaded and it seems to be working fine. To optimize the zip file further, I dropped the ~/deps folder as well as the build/Release/object.target folder which significantly reduced the size of the zip file.

I'll likely create a blog post or document more instructions - but hopefully this overview can get you started.
