### ISSUE TITLE
How to tell if the lib uses /dev/random or /dev/urandom?

### ISSUE THREAD

**Issue by JoHuang** [paixaop/node-sodium#134]
Hi 

My docker file is FROM node:8-alpine.
I would like to make sure which random the lib compiled.
How to check it?

Thanks,
Jo

**Comment by paixaop** [comment]
This is a libsodium setting.
From the change log:

 - The JavaScript target doesn't require /dev/urandom or an external
randombytes() implementation any more. Other minor Emscripten-related
improvements have been made in order to support libsodium.js
 - Custom randombytes implementations do not need to provide their own
implementation of randombytes_uniform() any more. randombytes_stir()
and randombytes_close() can also be NULL pointers if they are not
required.
 - On Linux, getrandom(2) is being used instead of directly accessing
/dev/urandom, if the kernel supports this system call.
